FROM python

WORKDIR /app
COPY ./backend/requirements.txt .
RUN pip install -r requirements.txt

COPY ./backend /app

CMD ["uvicorn", "--host", "0.0.0.0", "--port", "80", "--env-file", ".env", "main:app"]
