version: "3"
services:
    app:
        build: app
        image: nsychev/tci
        volumes:
            - "./app:/app"
        ports:
            - "127.0.0.1:8126:5000"
        command: ["gunicorn", "-w", "2", "-b", "0.0.0.0:5000", "app:app"]
        restart: always
